version: '3.8'

services:
  fastapi_app:
    build: .
    image: product_informer_img:latest
    container_name: product_informer
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    restart: always